# Generated by Django 2.1.7 on 2019-04-24 06:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_image/default_profile_normal.png', upload_to=account.models.avatar_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='profile_image/default_header.png', upload_to=account.models.header_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(default='kreator kaskus', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
