# Generated by Django 2.1.7 on 2019-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190424_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='header',
            new_name='user_header',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='user_photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(default='kreator Batasibuk', max_length=30),
        ),
    ]
