# Generated by Django 2.1.7 on 2019-04-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190426_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, default='kreator Batasibuk', max_length=30),
        ),
    ]
