# Generated by Django 2.1.7 on 2019-04-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190426_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, default='Kreator Batasibuk', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
