# Generated by Django 2.1.7 on 2019-04-30 06:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190426_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_header',
            field=models.ImageField(default='profile_image/default_header.jpg', upload_to=account.models.header_path),
        ),
    ]
