# Generated by Django 2.1.7 on 2019-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sended'), (2, 'Received'), (3, 'Read')], default=1),
        ),
    ]
