# Generated by Django 2.1.7 on 2019-04-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='last_post',
        ),
        migrations.RemoveField(
            model_name='subforum',
            name='last_post',
        ),
    ]
