# Generated by Django 2.1.7 on 2019-03-31 16:09

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
