# Generated by Django 2.1.7 on 2019-03-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0003_auto_20190331_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subforum',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='subforum_posts', to='batasibuk_forum.SubForum'),
        ),
    ]
