# Generated by Django 2.1.7 on 2019-04-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0003_auto_20190424_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='forum_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
