# Generated by Django 2.1.7 on 2019-04-30 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batasibuk_forum', '0004_auto_20190429_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_recommends', to='batasibuk_forum.Post')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
