# Generated by Django 2.1.7 on 2019-05-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0005_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='recommender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
