# Generated by Django 2.1.7 on 2019-05-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0007_viewpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
