# Generated by Django 2.1.7 on 2019-04-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0010_auto_20190331_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='batasibuk_forum.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subforum_posts', to='batasibuk_forum.SubForum'),
        ),
    ]
