# Generated by Django 2.1.7 on 2019-04-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0012_auto_20190403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
