# Generated by Django 2.1.7 on 2019-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0014_auto_20190408_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
    ]
