# Generated by Django 2.1.7 on 2019-04-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0015_auto_20190408_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to='batasibuk_forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
