# Generated by Django 2.1.7 on 2019-04-17 14:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batasibuk_forum', '0017_viewpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_subscriber',
            name='subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subforum_subscribers', to='batasibuk_forum.SubForum'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
